<%@ Page Language="C#" AutoEventWireup="true" CodeFile="SelectContract.aspx.cs" Inherits="ContractManage_ContractPayend_SelectContract" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <script type="text/javascript" src="../../Script/jquery.js"></script>

    <script type="text/javascript" src="/StockManage/script/Config2.js"></script>

    <title>选择合同</title>

    <script type="text/javascript">
        function setVal(id,name)
        {        
            window.opener.document.getElementById("txtContractName").value=name;
            window.opener.document.getElementById("hdContractId").value=id;
            window.opener.document.getElementById("btnRe").click();
            window.close();
        }
    </script>

</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="tab">
                <tr>
                    <td class="headerrow">
                        选择收入合同</td>
                </tr>
                <tr>
                    <td valign="top" style="height: 500px;">
                        <table style="width: 100%; border: solid 0px red; height: 100%;" cellpadding="0"
                            cellspacing="0">
                            <tr>
                                <td style="width: 150px; vertical-align: top; border-right-color: Black; border-right-style: solid;
                                    border-right-width: 1px;">
                                    <div class="pagediv">
                                        <asp:TreeView ID="tvContract" ForeColor="Black" ImageSet="Msdn" ShowLines="true" ExpandDepth="-1" AutoGenerateDataBindings="false" OnSelectedNodeChanged="tvContract_SelectedNodeChanged" runat="server"><SelectedNodeStyle ForeColor="Red" BackColor="#E0E0E0" /><NodeStyle ForeColor="Black" /></asp:TreeView>
                                    </div>
                                </td>
                                <td style="width: 75%; vertical-align: top;">
                                    <div style="height: 25px; text-align:right;" class="bottonrow">
                                        <asp:Button ID="btnSave" Text="保 存" OnClick="btnSave_Click" runat="server" />
                                        <input type="button" id="btnCancel" value="取 消" onclick="window.close();" />
                                    </div>
                                    <table class="viewTable" cellpadding="0" style="width: 99%;" align="center" cellspacing="0">
                                        <tr align="center">
                                            <td colspan="4">
                                                <asp:Label ID="lblContractTitle" Text="合同信息" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="width: 20%">
                                                合同名称
                                            </td>
                                            <td style="width: 30%">
                                                <asp:Label ID="lblContractName" runat="server"></asp:Label>
                                            </td>
                                            <td style="width: 20%">
                                                合同编号
                                            </td>
                                            <td style="width: 30%">
                                                <asp:Label ID="lblContractCode" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="width: 20%">
                                                合同金额
                                            </td>
                                            <td style="width: 30%">
                                                <asp:Label ID="lblContractPrice" runat="server"></asp:Label>
                                            </td>
                                            <td style="width: 20%">
                                                签订时间
                                            </td>
                                            <td style="width: 30%">
                                                <asp:Label ID="lblSinedTime" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>            
            </table>
        </div>
    </form>
</body>
</html>
