<%@ Page Language="C#" AutoEventWireup="true" CodeFile="InstitutionListSearch.aspx.cs" Inherits="Enterprise_InstitutionList" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server"><title>企业制度</title>
    <style type="text/css">
        span
        {
            text-decoration: underline;
            color: Blue;
            cursor: pointer;
        }
    </style>

    <script type="text/javascript" src="/SysFrame/jscript/JsControlMenuTool.js"></script>

    <script type="text/javascript">
        function openView(inscode) {
            var uri = "InstitutionView.aspx?ic=" + inscode;
            var fth = "width=640px,height=400px,location=no,menubar=no,toolsbar=no,status=no,resizable=yes";
            window.open(uri, '', fth);
        }
        function openEdit(op) {
            var uri = "InstitutionListEdit.aspx?ic=" + document.getElementById("HdnInsCode").value + "&op=" + op;
            var fth = "width=720px,height=500px,location=no,menubar=no,toolsbar=no,status=no";
            window.open(uri, '', fth);
        }
        function rowClick(insCode, status) {
            document.getElementById("BtnDelete").disabled = false;
            if (status == "-1") {
                document.getElementById("btnViewPurview").disabled = true;
                document.getElementById("BtnWF_Purview").disabled = false;
                document.getElementById("btnEdit").disabled = false;
            }
            if (status == "1" || status == "-2") {
                document.getElementById("btnViewPurview").disabled = false;
                document.getElementById("BtnWF_Purview").disabled = true;
                document.getElementById("btnEdit").disabled = true;
            }
            document.getElementById("HdnInsCode").value = insCode;
        }
        function OpenViewWF(BusinessCode, BusinessClass) {
            var rid = document.getElementById('HdnInsCode').value;
            var url = "/ModuleSet/Workflow/AuditViewWF.aspx?ic=" + rid + '&bc=' + BusinessCode + '&bcl=' + BusinessClass;
            return window.showModalDialog(url, window, "dialogHeight:460px;dialogWidth:600px;center:1;help:0;status:0;");
        }

        function viewInstitutions(insCode) {
            parent.desktop.viewInstitutions = window;
            var url = "/oa/System/Institution/InstitutionView.aspx?ic=" + insCode;
            toolbox_oncommand(url, "制度查看");
        }
        
    </script>

</head>
<body class="body_clear">
    <form id="form1" runat="server">
    <table class="table-normal" style="width: 100%; height: 613px;" border="1">
        <tr>
            <td style="width: 160px; vertical-align: top;">
                <div style="width: 100%; height: 100%; overflow: auto; margin-top: 15px;">
                    <asp:TreeView ID="TVInsClass" ExpandDepth="1" ForeColor="Black" ShowLines="true" AutoGenerateDataBindings="false" OnSelectedNodeChanged="TVInsClass_SelectedNodeChanged" runat="server"><HoverNodeStyle ForeColor="Red" /><SelectedNodeStyle ForeColor="Red" /><NodeStyle ForeColor="Black" /></asp:TreeView>
                </div>
            </td>
            <td style="vertical-align: top;">
                <table class="table-normal" style="width: 100%; vertical-align: top" border="1" cellspacing="0">
                    <tr>
                        <td class="td-head">
                            企业制度
                        </td>
                    </tr>
                    <tr>
                        <td class="td-search" style="height: 16px">
                            <!--名称<asp:TextBox ID="txtInsName" Height="18px" Width="100px" runat="server"></asp:TextBox>
                            编号<asp:TextBox ID="txtInsCode" Height="18px" Width="100px" runat="server"></asp:TextBox>
                            签发人<asp:TextBox ID="txtIssuPerson" Height="18px" Width="100px" runat="server"></asp:TextBox>-->
                            <JWControl:DateBox ID="txtStartDate" Width="100px" Visible="false" runat="server"></JWControl:DateBox>
                            <JWControl:DateBox ID="txtEndDate" Width="100px" Visible="false" runat="server"></JWControl:DateBox>
                            搜索：<asp:TextBox ID="txtcontent" Height="14px" Width="100px" runat="server"></asp:TextBox>
                            <asp:DropDownList ID="ddl_Search" Height="20px" Width="80px" runat="server"><asp:ListItem Value="InsName" Text="名称" /><asp:ListItem Value="UniqueCode" Text="编号" /><asp:ListItem Value="IssuePerson" Text="签发人" /></asp:DropDownList>
                            <asp:Button ID="BtnSearch" Text="查 询" CssClass="button-normal" OnClick="BtnSearch_Click" runat="server" />
                        </td>
                    </tr>
                    <tr style="display: none;">
                        <td class="td-toolsbar">
                            <input id="btnAdd" type="button" value="新 增" onclick="openEdit('Add');" />
                            <input type="button" id="btnEdit" value=" 编 辑" disabled="disabled" onclick="openEdit('Edit');" />
                            <asp:Button ID="BtnDelete" Text="删 除" Enabled="false" OnClick="BtnDelete_Click" runat="server" />
                            <asp:Button ID="BtnWF_Purview" Text="提交审核" Enabled="false" OnClick="BtnWF_Purview_Click" runat="server" />
                            <input id="btnViewPurview" type="button" value="查看审核" onclick="OpenViewWF('069','001')"
                                disabled="disabled" />
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: top;">
                            <div style="overflow: auto;">
                                <asp:GridView ID="GVInsList" CssClass="grid" Width="100%" AllowPaging="true" AutoGenerateColumns="false" PageSize="25" OnPageIndexChanging="GVInsList_PageIndexChanging" OnRowDataBound="GVInsList_RowDataBound" runat="server">
<EmptyDataTemplate>
                                        <table class="grid" cellspacing="0" rules="all" border="0" cellpadding="0" style="border-collapse: collapse;">
                                            <tr class="grid_head">
                                                <th style="width: 25px">
                                                    序号
                                                </th>
                                                <th>
                                                    编号
                                                </th>
                                                <th>
                                                    名称
                                                </th>
                                                <th>
                                                    签发人
                                                </th>
                                                <th>
                                                    签发日期
                                                </th>
                                                <th>
                                                    流程状态
                                                </th>
                                                <th>
                                                    发布时间
                                                </th>
                                            </tr>
                                        </table>
                                    </EmptyDataTemplate>
<Columns><asp:BoundField HeaderText="序号" /><asp:BoundField DataField="UniqueCode" HeaderText="编号" ItemStyle-Width="160px" /><asp:BoundField DataField="InsName" HeaderText="名称" /><asp:BoundField DataField="IssuePerson" HeaderText="签发人" /><asp:BoundField DataField="IssueDate" HeaderText="签发日期" DataFormatString="{0:yyyy-MM-dd}" HtmlEncode="false" /><asp:BoundField DataField="status" HeaderText="流程状态" /><asp:BoundField DataField="writedate" HeaderText="发布时间" /></Columns><RowStyle CssClass="grid_row"></RowStyle><HeaderStyle CssClass="grid_head"></HeaderStyle></asp:GridView>
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <input type="hidden" id="HdnLeveCode" style="width: 1px" runat="server" />

    <input type="hidden" id="HdnInsCode" style="width: 1px" runat="server" />

    </form>
</body>
</html>
