CREATE TABLE "PLUS_PROJECT" 
   (	"UID_" VARCHAR2(100), 
	"NAME_" VARCHAR2(100), 
	"STARTDATE_" DATE, 
	"FINISHDATE_" DATE, 
	"LASTSAVED_" VARCHAR2(20), 
	"CALENDARS_" CLOB, 
	"CALENDARUID_" VARCHAR2(50)
   );
   
CREATE TABLE "PLUS_RESOURCE" 
   (	"UID_" VARCHAR2(50), 
	"NAME_" VARCHAR2(50), 
	"TYPE_" NUMBER, 
	"MAXUNITS_" NUMBER, 
	"PROJECTUID_" VARCHAR2(50)
   );
   
CREATE TABLE "PLUS_TASK" 
   (	"UID_" VARCHAR2(50), 
	"ID_" NUMBER, 
	"NAME_" VARCHAR2(200), 
	"START_" DATE, 
	"FINISH_" DATE, 
	"DURATION_" NUMBER, 
	"WORK_" NUMBER, 
	"PERCENTCOMPLETE_" NUMBER, 
	"WEIGHT_" NUMBER, 
	"CONSTRAINTTYPE_" NUMBER, 
	"CONSTRAINTDATE_" DATE, 
	"MILESTONE_" NUMBER, 
	"SUMMARY_" NUMBER, 
	"CRITICAL_" NUMBER, 
	"PRIORITY_" NUMBER, 
	"NOTES_" VARCHAR2(2000), 
	"DEPARTMENT_" VARCHAR2(50), 
	"PRINCIPAL_" VARCHAR2(500), 
	"PREDECESSORLINK_" VARCHAR2(1000), 
	"FIXEDDATE_" NUMBER, 
	"PARENTTASKUID_" VARCHAR2(50), 
	"PROJECTUID_" VARCHAR2(50), 
	"ACTUALSTART_" DATE, 
	"ACTUALFINISH_" DATE, 
	"ACTUALDURATION_" NUMBER, 
	"ASSIGNMENTS_" VARCHAR2(2000),
	"WBS_" VARCHAR2(200),
	"CRITICAL2_" NUMBER
   );
   