--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : 星期五, 13 六月, 2014 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_BudCostAccounting_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_BudCostAccounting DROP CONSTRAINT FK_Equ_BudCostAccounting_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_ConnectionItem_Equ_RepairCompanyInfo') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_ConnectionItem DROP CONSTRAINT FK_Equ_ConnectionItem_Equ_RepairCompanyInfo
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_CutterProReport_Equ_ShipDayReport') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_CutterProReport DROP CONSTRAINT FK_Equ_CutterProReport_Equ_ShipDayReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_GrapProReport_Equ_ShipDayReport') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_GrapProReport DROP CONSTRAINT FK_Equ_GrapProReport_Equ_ShipDayReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_RepairPlan_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_RepairPlan DROP CONSTRAINT FK_Equ_RepairPlan_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_RepairReport_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_RepairReport DROP CONSTRAINT FK_Equ_RepairReport_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_RepairStock_Equ_RepairReport') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_RepairStock DROP CONSTRAINT FK_Equ_RepairStock_Equ_RepairReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_ShipDayReport_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_ShipDayReport DROP CONSTRAINT FK_Equ_ShipDayReport_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_ShipMonthReport_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_ShipMonthReport DROP CONSTRAINT FK_Equ_ShipMonthReport_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_ShipOilRecord_Equ_ShipRefuelApply') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_ShipOilRecord DROP CONSTRAINT FK_Equ_ShipOilRecord_Equ_ShipRefuelApply
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_ShipRefuelApply_Equ_Equipment') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_ShipRefuelApply DROP CONSTRAINT FK_Equ_ShipRefuelApply_Equ_Equipment
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_TeamReport_Equ_ShipDayReport') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_TeamReport DROP CONSTRAINT FK_Equ_TeamReport_Equ_ShipDayReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Equ_TrailingProReport_Equ_ShipDayReport') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Equ_TrailingProReport DROP CONSTRAINT FK_Equ_TrailingProReport_Equ_ShipDayReport
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_BudCostAccounting') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_BudCostAccounting
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_ConnectionItem') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_ConnectionItem
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_CutterProReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_CutterProReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_GrapProReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_GrapProReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_RepairApply') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_RepairApply
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_RepairCompanyInfo') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_RepairCompanyInfo
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_RepairPlan') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_RepairPlan
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_RepairReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_RepairReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_RepairStock') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_RepairStock
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_ShipDayReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_ShipDayReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_ShipMonthReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_ShipMonthReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_ShipOilRecord') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_ShipOilRecord
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_ShipRefuelApply') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_ShipRefuelApply
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_TeamReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_TeamReport
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Equ_TrailingProReport') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Equ_TrailingProReport
;


--  Create Tables 
CREATE TABLE Equ_BudCostAccounting ( 
	BudId nvarchar(64) NOT NULL,    --  BudId 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	ReportUser nvarchar(50) NOT NULL,    --  上报人 
	ReportDate datetime NOT NULL,    --  上报日期 
	UpkeepAnnexId nvarchar(100),    --  维修费附件Id 
	MaintenanceCosts decimal(18,3),    --  检修费 
	SmallRepairCosts decimal(18,3),    --  小修费 
	SailRepairCosts decimal(18,3),    --  航修费 
	EngineRepairCosts decimal(18,3),    --  机械维修费 
	MaterialsAnnexId nvarchar(100),    --  辅助材料费附件Id 
	OilCosts decimal(18,3),    --  机油费 
	CleaningCosts decimal(18,3),    --  除污、除锈材料费 
	WaterCosts decimal(18,3),    --  淡水费 
	AccessoriesCosts decimal(18,3),    --  配件费 
	PipeAndGraftAnnexId nvarchar(100),    --  管线安装、移接费用附件Id 
	LabourCosts decimal(18,3),    --  人工费 
	MaterialsCosts decimal(18,3),    --  材料费 
	EngineCosts decimal(18,3),    --  机械费 
	LabourAnnexId nvarchar(100),    --  人工费附件Id 
	MealsCosts decimal(18,3),    --  伙食费 
	WorkerWelfareCosts decimal(18,3),    --  职工福利费 
	TrafficCosts decimal(18,3),    --  交通补助费 
	LaborProtecteCosts decimal(18,3),    --  劳动保护费 
	PowerAnnexId nvarchar(100),    --  动力费附件Id 
	FuelCosts decimal(18,3),    --  燃油费 
	OtherCosts decimal(18,3),    --  其它费用 
	FlowState int DEFAULT -1 NOT NULL,
	InputUser nvarchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_ConnectionItem ( 
	ConnectionId nvarchar(64) NOT NULL,    --  维修申请、维修上报Id 
	ItemCode nvarchar(64) NOT NULL    --  项目编码 
)
;

CREATE TABLE Equ_CutterProReport ( 
	ProductionId nvarchar(64) NOT NULL,    --  产量Id 
	DayId nvarchar(100) NOT NULL,    --  DayId 
	Location_X decimal(18,3),    --  24小时坐标（X） 
	Location_Y decimal(18,3),    --  24小时坐标（Y） 
	Longth decimal(18,3),    --  分层厚度 
	Width decimal(18,3),    --  挖槽宽度 
	Height decimal(18,3),    --  进尺 
	ReportQty decimal(18,3),    --  方量 
	UnitPrice decimal(18,3)    --  单价 
)
;

CREATE TABLE Equ_GrapProReport ( 
	ProductionId nvarchar(64) NOT NULL,    --  产量ID 
	DayId nvarchar(100) NOT NULL,    --  DayId 
	EquId nvarchar(64) NOT NULL,    --  泥驳船ID 
	ShipCapaticy decimal(18,3) NOT NULL,    --  舱容 
	WorkCount decimal(18,3),    --  运泥驳数 
	TotalDeductQty decimal(18,3),    --  总扣方 
	DayReportQty decimal(18,3),    --  日报方量 
	DeductQty decimal(18,3),    --  未满载时扣方 
	UnitPrice decimal(18,3)    --  单价 
)
;

CREATE TABLE Equ_RepairApply ( 
	ApplyId nvarchar(64) NOT NULL,    --  维修申请单Id 
	RepairId nvarchar(64),    --  维修计划Id 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	LastRepairDate datetime,    --  上次维修日期 
	LastRepairContents nvarchar(500),    --  上次维修内容 
	LastRepairCosts decimal(18,3),    --  上次维修费用 
	PlanRepairCosts decimal(18,3) NOT NULL,    --  本次预计费维修用 
	PlanStartDate datetime NOT NULL,    --  本次预计开始时间 
	PlanEndDate datetime NOT NULL,    --  本次预计结束时间 
	PlanRepareContents nvarchar(500),    --  本次维修内容 
	ApplyUser nvarchar(50),    --  申请人 
	ApplyDate datetime,    --  申请日期 
	RepairType int NOT NULL,    --  1：自行维修；2：委外维修；3：自修、委外 
	RepairFlag int NOT NULL,    --  维修标识 
	RepairPlaceFlag int NOT NULL,    --  1：上坞；2：披滩；3：原地； 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	InputUser varchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_RepairCompanyInfo ( 
	ItemCode nvarchar(64) NOT NULL,    --  维修项目/公司编码 
	ParentCode nvarchar(64),    --  亲项目编码 
	ItemName nvarchar(50) NOT NULL,    --  项目名称/公司名称 
	UnitPrice decimal(18,3),    --  报价 
	Address nvarchar(200),    --  公司地址 
	Note nvarchar(500)    --  备注 
)
;

CREATE TABLE Equ_RepairPlan ( 
	RepairId nvarchar(64) NOT NULL,    --  Id 
	RepairCode nvarchar(64) NOT NULL,    --  维修计划单号 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	RepairPlanCosts decimal(18,3) NOT NULL,    --  预估花费 
	RepairContents nvarchar(500),    --  计划维修内容 
	RepairStartDate datetime,    --  维修开始时间 
	RepairEndDate datetime,    --  维修结束时间 
	RepairType int NOT NULL,    --  自行维修：1 委外维修：2 自修、委外：3 
	RepairFlag int NOT NULL,    --  1：检修；2：小修；3：航修；4：其他； 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	ApplyUser nvarchar(50),    --  计划编写人 
	DepNo int,    --  编写人部门 
	InputUser varchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_RepairReport ( 
	ReportId nvarchar(64) NOT NULL,    --  上报ID 
	ApplyId nvarchar(64),    --  维修申请ID 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	ReportDate datetime NOT NULL,    --  上报日期 
	RepairType int NOT NULL,    --  1：自行维修；2：委外维修；3：自修、委外 
	FaultDescription nvarchar(500),    --  故障简介 
	RepairStartDate datetime NOT NULL,    --  维修开始时间 
	RepairEndDate datetime NOT NULL,    --  维修结束时间 
	RepairPerson nvarchar(50),    --  维修人员 
	Reason nvarchar(max),    --  原因分析 
	OutCompany nvarchar(500),    --  委外维修公司 
	OutDepartment nvarchar(500),    --  委外维修部门 
	ContractId nvarchar(64),    --  委外维修合同 
	OutSubContractor nvarchar(500),    --  委外分包商 
	LaborCost decimal(18,3) NOT NULL,    --  人工费 
	MaterialCost decimal(18,3) NOT NULL,    --  材料费 
	OtherBudCostType int,    --  -1：未选中；0：上下坞费；1：电费；2：水费；3：垃圾处理费；4：安保费； 
	OtherBudCosts decimal(18,3),    --  其他间接费用 
	Acceptor nvarchar(50),    --  验收人 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	InputUser char(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_RepairStock ( 
	StockId nvarchar(64) NOT NULL,    --  维修零部件ID 
	ReportId nvarchar(64) NOT NULL,    --  维修上报Id 
	ResourceId nvarchar(500) NOT NULL,    --  零部件ID 
	Quantity decimal(18,3) NOT NULL,    --  数量 
	UnitPrice decimal(18,3) NOT NULL,    --  单价 
	CorpId nvarchar(64),    --  供应商 
	ReceivePerson char(8) NOT NULL,    --  领用人 
	ReceiveDate datetime NOT NULL    --  领用时间 
)
;

CREATE TABLE Equ_ShipDayReport ( 
	DayId nvarchar(100) NOT NULL,    --  当天日期+Guid编码 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	ReportDate datetime NOT NULL,    --  上报日期 
	ConstructionDate datetime,    --  施工日期 
	PrjId nvarchar(500) NOT NULL,    --  项目Id 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	WorkDurationT1 decimal(18,3),    --  运转时间（T1） 
	WorkRestDurationT2 decimal(18,3),    --  生产性间歇时间T2 
	NotWorkRestDurationT3 decimal(18,3),    --  非生产性间歇时间T3 
	DayOilWear decimal(18,3),    --  当日耗油量 
	OutputValueType int NOT NULL,    --  产值统计方式（-1：均未勾选；0:按产量；1：按台班；2：全部勾选） 
	CalculateType int,    --  产量计算方式 
	IsTeamInfo int NOT NULL,    --  台班计费时产量信息 
	DiscountRate decimal(18,3),    --  折扣率 
	InputUser varchar(8) NOT NULL,    --  记录人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_ShipMonthReport ( 
	MonthId nvarchar(64) NOT NULL,    --  MonthId 
	PrjId nvarchar(500) NOT NULL,    --  项目Id 
	EquId nvarchar(64) NOT NULL,    --  设备Id 
	StartMappingNo nvarchar(60),    --  期初浚前测图编号 
	EndMappingNo nvarchar(60),    --  期末浚后测图编号 
	MonthMappingQty decimal(18,3),    --  本期测图计算水下方 
	UnitPrice decimal(18,3),    --  单价 
	StartDate datetime,    --  期初测量时间 
	EndDate datetime,    --  期末测量时间 
	InputUser nvarchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_ShipOilRecord ( 
	RecordId nvarchar(64) NOT NULL,    --  RecordId 
	ApplyId nvarchar(64) NOT NULL,    --  加油申请单Id 
	BeforeHeight decimal(18,3),    --  加油前船舶油舱库存油高 
	AfterHeight decimal(18,3),    --  加油后船舶油舱油高 
	ApprovalOilQty decimal(18,3) NOT NULL,    --  批准加油量 
	ShipDisplayQty decimal(18,3),    --  供油船油表显示加油数量 
	FinalOilQty decimal(18,3) NOT NULL,    --  本次加油最终三方确认加油数量 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	ReportUser nvarchar(50),    --  上报人 
	ReportDate datetime,    --  上报日期 
	InputUser varchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_ShipRefuelApply ( 
	ApplyId nvarchar(64) NOT NULL,    --  申请ID 
	PrjId nvarchar(500) NOT NULL,    --  项目ID 
	EquId nvarchar(64) NOT NULL,    --  设备ID 
	RefuelPlace nvarchar(100),    --  申请加油地点 
	Sump decimal(18,3),    --  施工区域挖深 
	RefuelStartDate datetime NOT NULL,    --  加油开始时间 
	RefuelEndDate datetime NOT NULL,    --  加油结束时间 
	ApplyQuantity decimal(18,3) NOT NULL,    --  申请加油量 
	ResidualOil decimal(18,3) NOT NULL,    --  申请时剩余油量 
	EstimatedQuantity decimal(18,3),    --  预计工程量 
	NotCompletedQuantity decimal(18,3),    --  剩余工程量 
	ApplyRefuelDate datetime NOT NULL,    --  申请加油时间 
	FlowState int DEFAULT -1 NOT NULL,    --  流程状态 
	IsEntrustPurchase bit NOT NULL,    --  是否委托采购 
	ReportUser nvarchar(50),    --  上报人 
	ReportDate datetime,    --  上报日期 
	InputUser varchar(8) NOT NULL,    --  录入人 
	InputDate datetime DEFAULT Getdate() NOT NULL,    --  录入时间 
	Note nvarchar(max)    --  备注 
)
;

CREATE TABLE Equ_TeamReport ( 
	TeamID nvarchar(64) NOT NULL,    --  台班ID 
	UnitPrice decimal(18,3) NOT NULL,    --  单价 
	WorkDuration decimal(18,3) NOT NULL,    --  有效计费时长 
	ContractID nvarchar(64),    --  支出合同ID 
	DayId nvarchar(100) NOT NULL    --  DayId 
)
;

CREATE TABLE Equ_TrailingProReport ( 
	ProductionId nvarchar(64) NOT NULL,    --  产量Id 
	DayId nvarchar(100) NOT NULL,    --  DayId 
	SailNo nvarchar(60),    --  航次编号 
	ShipCapaticy decimal(18,3),    --  产量计装舱量 
	UnitPrice decimal(18,3)    --  单价 
)
;


--  Create Primary Key Constraints 
ALTER TABLE Equ_BudCostAccounting ADD CONSTRAINT PK_EquBudCostAccounting 
	PRIMARY KEY CLUSTERED (BudId)
;

ALTER TABLE Equ_ConnectionItem ADD CONSTRAINT PK_ConnectionItem 
	PRIMARY KEY CLUSTERED (ConnectionId, ItemCode)
;

ALTER TABLE Equ_CutterProReport ADD CONSTRAINT PK_Equ_CutterProReport 
	PRIMARY KEY CLUSTERED (ProductionId)
;

ALTER TABLE Equ_GrapProReport ADD CONSTRAINT PK_Equ_GrapProReport 
	PRIMARY KEY CLUSTERED (ProductionId)
;

ALTER TABLE Equ_RepairApply ADD CONSTRAINT PK_Equ_RepairApply 
	PRIMARY KEY CLUSTERED (ApplyId)
;

ALTER TABLE Equ_RepairCompanyInfo ADD CONSTRAINT PK_Equ_RepairCompanyInfo 
	PRIMARY KEY CLUSTERED (ItemCode)
;

ALTER TABLE Equ_RepairPlan ADD CONSTRAINT PK_Equ_RepairPlan 
	PRIMARY KEY CLUSTERED (RepairId)
;

ALTER TABLE Equ_RepairReport ADD CONSTRAINT PK_Equ_RepairReport 
	PRIMARY KEY CLUSTERED (ReportId)
;

ALTER TABLE Equ_RepairStock ADD CONSTRAINT PK_Equ_RepairStock 
	PRIMARY KEY CLUSTERED (StockId)
;

ALTER TABLE Equ_ShipDayReport ADD CONSTRAINT PK_Equ_ShipDayReport 
	PRIMARY KEY CLUSTERED (DayId)
;

ALTER TABLE Equ_ShipMonthReport ADD CONSTRAINT PK_Equ_ShipMonthReport 
	PRIMARY KEY CLUSTERED (MonthId)
;

ALTER TABLE Equ_ShipOilRecord ADD CONSTRAINT PK_ShipOilRecord 
	PRIMARY KEY CLUSTERED (RecordId)
;

ALTER TABLE Equ_ShipRefuelApply ADD CONSTRAINT PK_Equ_RefuelApply 
	PRIMARY KEY CLUSTERED (ApplyId)
;

ALTER TABLE Equ_TeamReport ADD CONSTRAINT PK_Equ_TeamReport 
	PRIMARY KEY CLUSTERED (TeamID)
;

ALTER TABLE Equ_TrailingProReport ADD CONSTRAINT PK_Equ_TrailingProReport 
	PRIMARY KEY CLUSTERED (ProductionId)
;


--  Create Indexes 
ALTER TABLE Equ_BudCostAccounting
	ADD CONSTRAINT UQ_EquBudCostAccounting_BudId UNIQUE (BudId)
;

ALTER TABLE Equ_CutterProReport
	ADD CONSTRAINT UQ_Equ_CutterProReport_ProductionId UNIQUE (ProductionId)
;

ALTER TABLE Equ_GrapProReport
	ADD CONSTRAINT UQ_Equ_GrapProReport_ProductionId UNIQUE (ProductionId)
;

ALTER TABLE Equ_RepairCompanyInfo
	ADD CONSTRAINT UQ_Equ_RepairCompanyInfo_ItemCode UNIQUE (ItemCode)
;

ALTER TABLE Equ_ShipDayReport
	ADD CONSTRAINT UQ_Equ_ShipDayReport_DayId UNIQUE (DayId)
;

ALTER TABLE Equ_ShipMonthReport
	ADD CONSTRAINT UQ_Equ_ShipMonthReport_MonthId UNIQUE (MonthId)
;

ALTER TABLE Equ_ShipOilRecord
	ADD CONSTRAINT UQ_ShipOilRecord_RecordId UNIQUE (RecordId)
;

ALTER TABLE Equ_ShipRefuelApply
	ADD CONSTRAINT UQ_ShipRefuelApply_ApplyId UNIQUE (ApplyId)
;

ALTER TABLE Equ_TeamReport
	ADD CONSTRAINT UQ_Equ_TeamReport_TeamID UNIQUE (TeamID)
;

ALTER TABLE Equ_TrailingProReport
	ADD CONSTRAINT UQ_Equ_TrailingProReport_ProductionId UNIQUE (ProductionId)
;


--  Create Foreign Key Constraints 
ALTER TABLE Equ_BudCostAccounting ADD CONSTRAINT FK_Equ_BudCostAccounting_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_ConnectionItem ADD CONSTRAINT FK_Equ_ConnectionItem_Equ_RepairCompanyInfo 
	FOREIGN KEY (ItemCode) REFERENCES Equ_RepairCompanyInfo (ItemCode)
;

ALTER TABLE Equ_CutterProReport ADD CONSTRAINT FK_Equ_CutterProReport_Equ_ShipDayReport 
	FOREIGN KEY (DayId) REFERENCES Equ_ShipDayReport (DayId)
;

ALTER TABLE Equ_GrapProReport ADD CONSTRAINT FK_Equ_GrapProReport_Equ_ShipDayReport 
	FOREIGN KEY (DayId) REFERENCES Equ_ShipDayReport (DayId)
;

ALTER TABLE Equ_RepairPlan ADD CONSTRAINT FK_Equ_RepairPlan_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_RepairReport ADD CONSTRAINT FK_Equ_RepairReport_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_RepairStock ADD CONSTRAINT FK_Equ_RepairStock_Equ_RepairReport 
	FOREIGN KEY (ReportId) REFERENCES Equ_RepairReport (ReportId)
;

ALTER TABLE Equ_ShipDayReport ADD CONSTRAINT FK_Equ_ShipDayReport_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_ShipMonthReport ADD CONSTRAINT FK_Equ_ShipMonthReport_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_ShipOilRecord ADD CONSTRAINT FK_Equ_ShipOilRecord_Equ_ShipRefuelApply 
	FOREIGN KEY (ApplyId) REFERENCES Equ_ShipRefuelApply (ApplyId)
;

ALTER TABLE Equ_ShipRefuelApply ADD CONSTRAINT FK_Equ_ShipRefuelApply_Equ_Equipment 
	FOREIGN KEY (EquId) REFERENCES Equ_Equipment (Id)
;

ALTER TABLE Equ_TeamReport ADD CONSTRAINT FK_Equ_TeamReport_Equ_ShipDayReport 
	FOREIGN KEY (DayId) REFERENCES Equ_ShipDayReport (DayId)
;

ALTER TABLE Equ_TrailingProReport ADD CONSTRAINT FK_Equ_TrailingProReport_Equ_ShipDayReport 
	FOREIGN KEY (DayId) REFERENCES Equ_ShipDayReport (DayId)
;









EXEC sp_addextendedproperty 'MS_Description', '设备成本信息', 'Schema', dbo, 'table', Equ_BudCostAccounting
;
EXEC sp_addextendedproperty 'MS_Description', 'BudId', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', BudId
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '上报人', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', ReportUser
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', ReportDate
;

EXEC sp_addextendedproperty 'MS_Description', '维修费附件Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', UpkeepAnnexId
;

EXEC sp_addextendedproperty 'MS_Description', '检修费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', MaintenanceCosts
;

EXEC sp_addextendedproperty 'MS_Description', '小修费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', SmallRepairCosts
;

EXEC sp_addextendedproperty 'MS_Description', '航修费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', SailRepairCosts
;

EXEC sp_addextendedproperty 'MS_Description', '机械维修费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', EngineRepairCosts
;

EXEC sp_addextendedproperty 'MS_Description', '辅助材料费附件Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', MaterialsAnnexId
;

EXEC sp_addextendedproperty 'MS_Description', '机油费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', OilCosts
;

EXEC sp_addextendedproperty 'MS_Description', '除污、除锈材料费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', CleaningCosts
;

EXEC sp_addextendedproperty 'MS_Description', '淡水费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', WaterCosts
;

EXEC sp_addextendedproperty 'MS_Description', '配件费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', AccessoriesCosts
;

EXEC sp_addextendedproperty 'MS_Description', '管线安装、移接费用附件Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', PipeAndGraftAnnexId
;

EXEC sp_addextendedproperty 'MS_Description', '人工费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', LabourCosts
;

EXEC sp_addextendedproperty 'MS_Description', '材料费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', MaterialsCosts
;

EXEC sp_addextendedproperty 'MS_Description', '机械费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', EngineCosts
;

EXEC sp_addextendedproperty 'MS_Description', '人工费附件Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', LabourAnnexId
;

EXEC sp_addextendedproperty 'MS_Description', '伙食费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', MealsCosts
;

EXEC sp_addextendedproperty 'MS_Description', '职工福利费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', WorkerWelfareCosts
;

EXEC sp_addextendedproperty 'MS_Description', '交通补助费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', TrafficCosts
;

EXEC sp_addextendedproperty 'MS_Description', '劳动保护费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', LaborProtecteCosts
;

EXEC sp_addextendedproperty 'MS_Description', '动力费附件Id', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', PowerAnnexId
;

EXEC sp_addextendedproperty 'MS_Description', '燃油费', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', FuelCosts
;

EXEC sp_addextendedproperty 'MS_Description', '其它费用', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', OtherCosts
;


EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_BudCostAccounting, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '维修申请、维修上报和维修项目的关联表', 'Schema', dbo, 'table', Equ_ConnectionItem
;
EXEC sp_addextendedproperty 'MS_Description', '维修申请、维修上报Id', 'Schema', dbo, 'table', Equ_ConnectionItem, 'column', ConnectionId
;

EXEC sp_addextendedproperty 'MS_Description', '项目编码', 'Schema', dbo, 'table', Equ_ConnectionItem, 'column', ItemCode
;

EXEC sp_addextendedproperty 'MS_Description', '绞吸式挖泥船产量', 'Schema', dbo, 'table', Equ_CutterProReport
;
EXEC sp_addextendedproperty 'MS_Description', '产量Id', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', ProductionId
;

EXEC sp_addextendedproperty 'MS_Description', 'DayId', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', DayId
;

EXEC sp_addextendedproperty 'MS_Description', '24小时坐标（X）', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', Location_X
;

EXEC sp_addextendedproperty 'MS_Description', '24小时坐标（Y）', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', Location_Y
;

EXEC sp_addextendedproperty 'MS_Description', '分层厚度', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', Longth
;

EXEC sp_addextendedproperty 'MS_Description', '挖槽宽度', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', Width
;

EXEC sp_addextendedproperty 'MS_Description', '进尺', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', Height
;

EXEC sp_addextendedproperty 'MS_Description', '方量', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', ReportQty
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_CutterProReport, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '抓扬式挖泥船产量', 'Schema', dbo, 'table', Equ_GrapProReport
;
EXEC sp_addextendedproperty 'MS_Description', '产量ID', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', ProductionId
;

EXEC sp_addextendedproperty 'MS_Description', 'DayId', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', DayId
;

EXEC sp_addextendedproperty 'MS_Description', '泥驳船ID', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '舱容', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', ShipCapaticy
;

EXEC sp_addextendedproperty 'MS_Description', '运泥驳数', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', WorkCount
;

EXEC sp_addextendedproperty 'MS_Description', '总扣方', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', TotalDeductQty
;

EXEC sp_addextendedproperty 'MS_Description', '日报方量', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', DayReportQty
;

EXEC sp_addextendedproperty 'MS_Description', '未满载时扣方', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', DeductQty
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_GrapProReport, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '维修申请单Id', 'Schema', dbo, 'table', Equ_RepairApply, 'column', ApplyId
;

EXEC sp_addextendedproperty 'MS_Description', '维修计划Id', 'Schema', dbo, 'table', Equ_RepairApply, 'column', RepairId
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_RepairApply, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '上次维修日期', 'Schema', dbo, 'table', Equ_RepairApply, 'column', LastRepairDate
;

EXEC sp_addextendedproperty 'MS_Description', '上次维修内容', 'Schema', dbo, 'table', Equ_RepairApply, 'column', LastRepairContents
;

EXEC sp_addextendedproperty 'MS_Description', '上次维修费用', 'Schema', dbo, 'table', Equ_RepairApply, 'column', LastRepairCosts
;

EXEC sp_addextendedproperty 'MS_Description', '本次预计费维修用', 'Schema', dbo, 'table', Equ_RepairApply, 'column', PlanRepairCosts
;

EXEC sp_addextendedproperty 'MS_Description', '本次预计开始时间', 'Schema', dbo, 'table', Equ_RepairApply, 'column', PlanStartDate
;

EXEC sp_addextendedproperty 'MS_Description', '本次预计结束时间', 'Schema', dbo, 'table', Equ_RepairApply, 'column', PlanEndDate
;

EXEC sp_addextendedproperty 'MS_Description', '本次维修内容', 'Schema', dbo, 'table', Equ_RepairApply, 'column', PlanRepareContents
;

EXEC sp_addextendedproperty 'MS_Description', '申请人', 'Schema', dbo, 'table', Equ_RepairApply, 'column', ApplyUser
;

EXEC sp_addextendedproperty 'MS_Description', '申请日期', 'Schema', dbo, 'table', Equ_RepairApply, 'column', ApplyDate
;

EXEC sp_addextendedproperty 'MS_Description', '1：自行维修；2：委外维修；3：自修、委外', 'Schema', dbo, 'table', Equ_RepairApply, 'column', RepairType
;

EXEC sp_addextendedproperty 'MS_Description', '维修标识', 'Schema', dbo, 'table', Equ_RepairApply, 'column', RepairFlag
;

EXEC sp_addextendedproperty 'MS_Description', '1：上坞；2：披滩；3：原地；', 'Schema', dbo, 'table', Equ_RepairApply, 'column', RepairPlaceFlag
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_RepairApply, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_RepairApply, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_RepairApply, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_RepairApply, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '维修公司信息', 'Schema', dbo, 'table', Equ_RepairCompanyInfo
;
EXEC sp_addextendedproperty 'MS_Description', '维修项目/公司编码', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', ItemCode
;

EXEC sp_addextendedproperty 'MS_Description', '亲项目编码', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', ParentCode
;

EXEC sp_addextendedproperty 'MS_Description', '项目名称/公司名称', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', ItemName
;

EXEC sp_addextendedproperty 'MS_Description', '报价', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '公司地址', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', Address
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_RepairCompanyInfo, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', 'Id', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairId
;

EXEC sp_addextendedproperty 'MS_Description', '维修计划单号', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairCode
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '预估花费', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairPlanCosts
;

EXEC sp_addextendedproperty 'MS_Description', '计划维修内容', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairContents
;

EXEC sp_addextendedproperty 'MS_Description', '维修开始时间', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairStartDate
;

EXEC sp_addextendedproperty 'MS_Description', '维修结束时间', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairEndDate
;

EXEC sp_addextendedproperty 'MS_Description', '自行维修：1
委外维修：2
自修、委外：3', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairType
;

EXEC sp_addextendedproperty 'MS_Description', '1：检修；2：小修；3：航修；4：其他；', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', RepairFlag
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '计划编写人', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', ApplyUser
;

EXEC sp_addextendedproperty 'MS_Description', '编写人部门', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', DepNo
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_RepairPlan, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '维修情况上报', 'Schema', dbo, 'table', Equ_RepairReport
;
EXEC sp_addextendedproperty 'MS_Description', '上报ID', 'Schema', dbo, 'table', Equ_RepairReport, 'column', ReportId
;

EXEC sp_addextendedproperty 'MS_Description', '维修申请ID', 'Schema', dbo, 'table', Equ_RepairReport, 'column', ApplyId
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_RepairReport, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Equ_RepairReport, 'column', ReportDate
;

EXEC sp_addextendedproperty 'MS_Description', '1：自行维修；2：委外维修；3：自修、委外', 'Schema', dbo, 'table', Equ_RepairReport, 'column', RepairType
;

EXEC sp_addextendedproperty 'MS_Description', '故障简介', 'Schema', dbo, 'table', Equ_RepairReport, 'column', FaultDescription
;

EXEC sp_addextendedproperty 'MS_Description', '维修开始时间', 'Schema', dbo, 'table', Equ_RepairReport, 'column', RepairStartDate
;

EXEC sp_addextendedproperty 'MS_Description', '维修结束时间', 'Schema', dbo, 'table', Equ_RepairReport, 'column', RepairEndDate
;

EXEC sp_addextendedproperty 'MS_Description', '维修人员', 'Schema', dbo, 'table', Equ_RepairReport, 'column', RepairPerson
;

EXEC sp_addextendedproperty 'MS_Description', '原因分析', 'Schema', dbo, 'table', Equ_RepairReport, 'column', Reason
;

EXEC sp_addextendedproperty 'MS_Description', '委外维修公司', 'Schema', dbo, 'table', Equ_RepairReport, 'column', OutCompany
;

EXEC sp_addextendedproperty 'MS_Description', '委外维修部门', 'Schema', dbo, 'table', Equ_RepairReport, 'column', OutDepartment
;

EXEC sp_addextendedproperty 'MS_Description', '委外维修合同', 'Schema', dbo, 'table', Equ_RepairReport, 'column', ContractId
;

EXEC sp_addextendedproperty 'MS_Description', '委外分包商', 'Schema', dbo, 'table', Equ_RepairReport, 'column', OutSubContractor
;

EXEC sp_addextendedproperty 'MS_Description', '人工费', 'Schema', dbo, 'table', Equ_RepairReport, 'column', LaborCost
;

EXEC sp_addextendedproperty 'MS_Description', '材料费', 'Schema', dbo, 'table', Equ_RepairReport, 'column', MaterialCost
;

EXEC sp_addextendedproperty 'MS_Description', '-1：未选中；0：上下坞费；1：电费；2：水费；3：垃圾处理费；4：安保费；', 'Schema', dbo, 'table', Equ_RepairReport, 'column', OtherBudCostType
;

EXEC sp_addextendedproperty 'MS_Description', '其他间接费用', 'Schema', dbo, 'table', Equ_RepairReport, 'column', OtherBudCosts
;

EXEC sp_addextendedproperty 'MS_Description', '验收人', 'Schema', dbo, 'table', Equ_RepairReport, 'column', Acceptor
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_RepairReport, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_RepairReport, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_RepairReport, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_RepairReport, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '维修零部件', 'Schema', dbo, 'table', Equ_RepairStock
;
EXEC sp_addextendedproperty 'MS_Description', '维修零部件ID', 'Schema', dbo, 'table', Equ_RepairStock, 'column', StockId
;

EXEC sp_addextendedproperty 'MS_Description', '维修上报Id', 'Schema', dbo, 'table', Equ_RepairStock, 'column', ReportId
;

EXEC sp_addextendedproperty 'MS_Description', '零部件ID', 'Schema', dbo, 'table', Equ_RepairStock, 'column', ResourceId
;

EXEC sp_addextendedproperty 'MS_Description', '数量', 'Schema', dbo, 'table', Equ_RepairStock, 'column', Quantity
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_RepairStock, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '供应商', 'Schema', dbo, 'table', Equ_RepairStock, 'column', CorpId
;

EXEC sp_addextendedproperty 'MS_Description', '领用人', 'Schema', dbo, 'table', Equ_RepairStock, 'column', ReceivePerson
;

EXEC sp_addextendedproperty 'MS_Description', '领用时间', 'Schema', dbo, 'table', Equ_RepairStock, 'column', ReceiveDate
;

EXEC sp_addextendedproperty 'MS_Description', '船舶设备日上报', 'Schema', dbo, 'table', Equ_ShipDayReport
;
EXEC sp_addextendedproperty 'MS_Description', '当天日期+Guid编码', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', DayId
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', ReportDate
;

EXEC sp_addextendedproperty 'MS_Description', '施工日期', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', ConstructionDate
;

EXEC sp_addextendedproperty 'MS_Description', '项目Id', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', PrjId
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '运转时间（T1）', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', WorkDurationT1
;

EXEC sp_addextendedproperty 'MS_Description', '生产性间歇时间T2', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', WorkRestDurationT2
;

EXEC sp_addextendedproperty 'MS_Description', '非生产性间歇时间T3', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', NotWorkRestDurationT3
;

EXEC sp_addextendedproperty 'MS_Description', '当日耗油量', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', DayOilWear
;

EXEC sp_addextendedproperty 'MS_Description', '产值统计方式（-1：均未勾选；0:按产量；1：按台班；2：全部勾选）', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', OutputValueType
;

EXEC sp_addextendedproperty 'MS_Description', '产量计算方式', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', CalculateType
;

EXEC sp_addextendedproperty 'MS_Description', '台班计费时产量信息', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', IsTeamInfo
;

EXEC sp_addextendedproperty 'MS_Description', '折扣率', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', DiscountRate
;

EXEC sp_addextendedproperty 'MS_Description', '记录人', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_ShipDayReport, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '月度水下方测量上报', 'Schema', dbo, 'table', Equ_ShipMonthReport
;
EXEC sp_addextendedproperty 'MS_Description', 'MonthId', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', MonthId
;

EXEC sp_addextendedproperty 'MS_Description', '项目Id', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', PrjId
;

EXEC sp_addextendedproperty 'MS_Description', '设备Id', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '期初浚前测图编号', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', StartMappingNo
;

EXEC sp_addextendedproperty 'MS_Description', '期末浚后测图编号', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', EndMappingNo
;

EXEC sp_addextendedproperty 'MS_Description', '本期测图计算水下方', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', MonthMappingQty
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '期初测量时间', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', StartDate
;

EXEC sp_addextendedproperty 'MS_Description', '期末测量时间', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', EndDate
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_ShipMonthReport, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '加油记录', 'Schema', dbo, 'table', Equ_ShipOilRecord
;
EXEC sp_addextendedproperty 'MS_Description', 'RecordId', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', RecordId
;

EXEC sp_addextendedproperty 'MS_Description', '加油申请单Id', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', ApplyId
;

EXEC sp_addextendedproperty 'MS_Description', '加油前船舶油舱库存油高', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', BeforeHeight
;

EXEC sp_addextendedproperty 'MS_Description', '加油后船舶油舱油高', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', AfterHeight
;

EXEC sp_addextendedproperty 'MS_Description', '批准加油量', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', ApprovalOilQty
;

EXEC sp_addextendedproperty 'MS_Description', '供油船油表显示加油数量', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', ShipDisplayQty
;

EXEC sp_addextendedproperty 'MS_Description', '本次加油最终三方确认加油数量', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', FinalOilQty
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '上报人', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', ReportUser
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', ReportDate
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_ShipOilRecord, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '加油申请', 'Schema', dbo, 'table', Equ_ShipRefuelApply
;
EXEC sp_addextendedproperty 'MS_Description', '申请ID', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ApplyId
;

EXEC sp_addextendedproperty 'MS_Description', '项目ID', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', PrjId
;

EXEC sp_addextendedproperty 'MS_Description', '设备ID', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', EquId
;

EXEC sp_addextendedproperty 'MS_Description', '申请加油地点', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', RefuelPlace
;

EXEC sp_addextendedproperty 'MS_Description', '施工区域挖深', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', Sump
;

EXEC sp_addextendedproperty 'MS_Description', '加油开始时间', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', RefuelStartDate
;

EXEC sp_addextendedproperty 'MS_Description', '加油结束时间', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', RefuelEndDate
;

EXEC sp_addextendedproperty 'MS_Description', '申请加油量', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ApplyQuantity
;

EXEC sp_addextendedproperty 'MS_Description', '申请时剩余油量', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ResidualOil
;

EXEC sp_addextendedproperty 'MS_Description', '预计工程量', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', EstimatedQuantity
;

EXEC sp_addextendedproperty 'MS_Description', '剩余工程量', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', NotCompletedQuantity
;

EXEC sp_addextendedproperty 'MS_Description', '申请加油时间', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ApplyRefuelDate
;

EXEC sp_addextendedproperty 'MS_Description', '流程状态', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', FlowState
;

EXEC sp_addextendedproperty 'MS_Description', '是否委托采购', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', IsEntrustPurchase
;

EXEC sp_addextendedproperty 'MS_Description', '上报人', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ReportUser
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', ReportDate
;

EXEC sp_addextendedproperty 'MS_Description', '录入人', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', InputUser
;

EXEC sp_addextendedproperty 'MS_Description', '录入时间', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', InputDate
;

EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', Equ_ShipRefuelApply, 'column', Note
;

EXEC sp_addextendedproperty 'MS_Description', '台班', 'Schema', dbo, 'table', Equ_TeamReport
;
EXEC sp_addextendedproperty 'MS_Description', '台班ID', 'Schema', dbo, 'table', Equ_TeamReport, 'column', TeamID
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_TeamReport, 'column', UnitPrice
;

EXEC sp_addextendedproperty 'MS_Description', '有效计费时长', 'Schema', dbo, 'table', Equ_TeamReport, 'column', WorkDuration
;

EXEC sp_addextendedproperty 'MS_Description', '支出合同ID', 'Schema', dbo, 'table', Equ_TeamReport, 'column', ContractID
;

EXEC sp_addextendedproperty 'MS_Description', 'DayId', 'Schema', dbo, 'table', Equ_TeamReport, 'column', DayId
;

EXEC sp_addextendedproperty 'MS_Description', '耙吸式挖泥船产量', 'Schema', dbo, 'table', Equ_TrailingProReport
;
EXEC sp_addextendedproperty 'MS_Description', '产量Id', 'Schema', dbo, 'table', Equ_TrailingProReport, 'column', ProductionId
;

EXEC sp_addextendedproperty 'MS_Description', 'DayId', 'Schema', dbo, 'table', Equ_TrailingProReport, 'column', DayId
;

EXEC sp_addextendedproperty 'MS_Description', '航次编号', 'Schema', dbo, 'table', Equ_TrailingProReport, 'column', SailNo
;

EXEC sp_addextendedproperty 'MS_Description', '产量计装舱量', 'Schema', dbo, 'table', Equ_TrailingProReport, 'column', ShipCapaticy
;

EXEC sp_addextendedproperty 'MS_Description', '单价', 'Schema', dbo, 'table', Equ_TrailingProReport, 'column', UnitPrice
;
