<%@ Page Language="C#" AutoEventWireup="true" CodeFile="InstitutionClass.aspx.cs" Inherits="Enterprise_InstitutionClass" %>


<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server"><title>公司制度</title>
    <script type="text/javascript">
        function rowClick(d, PerC, ucode, un) {
            document.getElementById("btnEdit").disabled = false;
            document.getElementById("BtnDelete").disabled = false;
            document.getElementById("HdnLeveCode").value = d;
            document.getElementById("HdnPerClass").value = PerC;
            document.getElementById("hdnUcode").value = ucode;
            document.getElementById("hdnUN").value = un;
        }
        function PerClassEdit(op) {
            var PerClass = document.getElementById("HdnPerClass").value;
            var ucode = document.getElementById("hdnUcode").value;
            var un = document.getElementById("hdnUN").value;
            var uri = "/oa/System/Institution/InstitutionClassEdit.aspx?op=" + op + "&lc=" + document.getElementById("HdnLeveCode").value;
            uri += "&ucode=" + ucode + "&un=" + un;
            top.ui.openWin({ title: '新增制度分类', url: uri, width: 400, height: 300 })
            //            window.open(uri, '', 'width=450px,height=230px,location=no,menubar=no,toolsbar=no,status=no');
        }
    </script>
</head>
<body class="body_clear" scroll="no">
    <form id="form1" runat="server">
    <table style="width: 100%; height: 100%;" class="table-normal" border="1">
        <tr>
            <td style="width: 150px; vertical-align: top;">
                <div style="overflow: auto; margin-top: 15px;">
                    <asp:TreeView ID="TVInsClass" ExpandDepth="1" ForeColor="Black" ShowLines="true" AutoGenerateDataBindings="false" OnSelectedNodeChanged="TVInsClass_SelectedNodeChanged" runat="server"><HoverNodeStyle ForeColor="Red" /><SelectedNodeStyle ForeColor="Red" /><NodeStyle ForeColor="Black" /></asp:TreeView>
                </div>
            </td>
            <td style="vertical-align: top;">
                <table style="width: 100%;" border="1" class="table-normal" cellspacing="0">
                    <tr>
                        <td class="td-head">
                            企业制度分类
                        </td>
                    </tr>
                    <tr style="display: none;">
                        <td class="td-search">
                            分类名称：<asp:TextBox ID="txtSearchName" runat="server"></asp:TextBox>
                            分类编码：<asp:TextBox ID="txtSearchCode" runat="server"></asp:TextBox>
                            <asp:Button ID="BtnSearch" Text="" OnClick="BtnSearch_Click" runat="server" />
                        </td>
                    </tr>
                    <tr>
                        <td class="td-toolsbar">
                            <input type="button" id="btnAdd" value="新 增" onclick="PerClassEdit('Add')" />
                            <input type="button" id="btnEdit" value="编 辑" disabled="disabled" onclick="PerClassEdit('Edit')" />
                            <asp:Button ID="BtnDelete" Text="删 除" Enabled="false" OnClick="BtnDelete_Click" runat="server" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:GridView ID="GVPermissionList" CssClass="grid" AllowPaging="true" AutoGenerateColumns="false" PageSize="13" Width="100%" OnRowDataBound="GVPermissionList_RowDataBound" OnPageIndexChanging="GVPermissionList_PageIndexChanging" DataKeyNames="LeveCode" runat="server">
<EmptyDataTemplate>
                                    <table class="grid" cellspacing="0" rules="all" border="1" style="border-collapse: collapse;">
                                        <tr class="grid_head">
                                            <th style="width: 25px">
                                                序号
                                            </th>
                                            <th>
                                                名称
                                            </th>
                                            <th>
                                                编码
                                            </th>
                                            <th>
                                                权限类别
                                            </th>
                                            <th>
                                                权限集合
                                            </th>
                                            <th>
                                                添加时间
                                            </th>
                                        </tr>
                                    </table>
                                </EmptyDataTemplate>
<Columns><asp:BoundField HeaderText="序号" /><asp:BoundField DataField="ClassName" HeaderText="分类名称" /><asp:BoundField DataField="ClassCode" HeaderText="分类编码" /><asp:BoundField HeaderText="权限类别" /><asp:TemplateField HeaderText="权限集合">
<ItemTemplate>
                                            <asp:TextBox ID="txtPersSet" TextMode="MultiLine" Width="100%" Height="16px" BorderWidth="0px" BackColor="Transparent" runat="server"></asp:TextBox>
                                        </ItemTemplate>
</asp:TemplateField><asp:BoundField DataField="WriteTime" HeaderText="添加日期" HtmlEncode="false" DataFormatString="{0:yyyy-MM-dd}" /><asp:TemplateField HeaderText="是否只读" HeaderStyle-Width="100px"><ItemTemplate>
                                            <%# ((bool)Eval("ReadOnly")) ? "是" : "否" %>
                                        </ItemTemplate></asp:TemplateField></Columns><RowStyle CssClass="grid_row"></RowStyle><HeaderStyle CssClass="grid_head"></HeaderStyle></asp:GridView>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <input type="hidden" id="HdnLeveCode" style="width: 1px;" runat="server" />

    <input type="hidden" id="HdnPerClass" style="width: 1px" runat="server" />

    <input type="hidden" id="hdnUcode" style="width: 1px" />
    <input type="hidden" id="hdnUN" style="width: 1px" />
    </form>
</body>
</html>
