<%@ Page Language="C#" AutoEventWireup="true" CodeFile="InsClassTree.aspx.cs" Inherits="Enterprise_InsClassTree" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server"><title>制度分类树</title>
    <script type="text/javascript">
     function setParentValue()
     {
        if(document.getElementById("txtSearch")!="")
        {
            window.opener.document.getElementById("txtClassName").value=document.getElementById("txtSearch").value;
            window.opener.document.getElementById("HdnClassCode").value=document.getElementById("HdnLeveCode").value;
        }
        window.close();
     }
    </script>
</head>
<body class="body_clear">
    <form id="form1" runat="server">
        <table class="table-normal" style="width:100%;height:100%;" border="1">
        <tr>
            <td class="td-head">
                制度分类
            </td>
        </tr>
        <tr>
            <td style="vertical-align:top;height:265px">
                <div style="width:100%;height:100%;overflow:auto;margin-left:20px;">
                    <asp:TreeView ID="TVInsClassTree" ForeColor="Black" ShowLines="true" AutoGenerateDataBindings="false" OnSelectedNodeChanged="TVInsClassTree_SelectedNodeChanged" runat="server"><HoverNodeStyle ForeColor="Red" /><SelectedNodeStyle ForeColor="Red" /><NodeStyle ForeColor="Black" /></asp:TreeView>
                </div>
            </td>
        </tr>
        <tr>
            <td style="text-align:center;">
                选择：<asp:TextBox ID="txtSearch" runat="server"></asp:TextBox>
                <input type="hidden" id="HdnLeveCode" style="width:1px;" runat="server" />

            </td>
        </tr>
        <tr>
            <td class="td-submit" style="text-align:center;">
                <input type="button" id="btnSave" value="确 定" onclick="setParentValue();"/>
            </td>
        </tr>
        </table>
    </form>
</body>
</html>
