--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : 星期一, 30 十二月, 2013 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Prj_Milestone') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Prj_Milestone
GO


--  Create Tables 
CREATE TABLE Prj_Milestone ( 
	Id nvarchar(200) NOT NULL,    --  ID 
	UserCode varchar(8) NOT NULL,    --  用户编码 
	RptDate datetime DEFAULT GETDATE() NOT NULL,    --  上报日期 
	StoreAmount decimal(18,3) DEFAULT 0.0 NOT NULL,    --  项目储备额（千元） 
	ForeCast decimal(18,3) DEFAULT 0.0 NOT NULL,    --  今年预测 
	StoreSwitchRate decimal(18,3) DEFAULT 0.0 NOT NULL,    --  储备转换率 
	NextForeCast decimal(18,3) DEFAULT 0.0 NOT NULL,    --  明年预测 
	Stone1 int DEFAULT 0 NOT NULL,    --  1初步接洽 
	Stone2 int DEFAULT 0 NOT NULL,    --  2提供样品 
	Stone3 int DEFAULT 0 NOT NULL,    --  3样品质量被接纳 
	Stone4 int DEFAULT 0 NOT NULL,    --  4投标 
	Stone5 int DEFAULT 0 NOT NULL,    --  5中标 
	Stone6 int DEFAULT 0 NOT NULL,    --  6下订单 
	Stone7 int DEFAULT 0 NOT NULL,    --  7交货 
	Stone8 int DEFAULT 0 NOT NULL,    --  8销售确认 
	Stone9 int DEFAULT 0 NOT NULL    --  9项目失败 
)
GO


--  Create Primary Key Constraints 
ALTER TABLE Prj_Milestone ADD CONSTRAINT PK_SP_Milestone 
	PRIMARY KEY CLUSTERED (Id)
GO











EXEC sp_addextendedproperty 'MS_Description', '项目里程碑报告', 'Schema', dbo, 'table', Prj_Milestone
GO
EXEC sp_addextendedproperty 'MS_Description', 'ID', 'Schema', dbo, 'table', Prj_Milestone, 'column', Id
GO

EXEC sp_addextendedproperty 'MS_Description', '用户编码', 'Schema', dbo, 'table', Prj_Milestone, 'column', UserCode
GO

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Prj_Milestone, 'column', RptDate
GO

EXEC sp_addextendedproperty 'MS_Description', '项目储备额（千元）', 'Schema', dbo, 'table', Prj_Milestone, 'column', StoreAmount
GO

EXEC sp_addextendedproperty 'MS_Description', '今年预测', 'Schema', dbo, 'table', Prj_Milestone, 'column', ForeCast
GO

EXEC sp_addextendedproperty 'MS_Description', '储备转换率', 'Schema', dbo, 'table', Prj_Milestone, 'column', StoreSwitchRate
GO

EXEC sp_addextendedproperty 'MS_Description', '明年预测', 'Schema', dbo, 'table', Prj_Milestone, 'column', NextForeCast
GO

EXEC sp_addextendedproperty 'MS_Description', '1初步接洽', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone1
GO

EXEC sp_addextendedproperty 'MS_Description', '2提供样品', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone2
GO

EXEC sp_addextendedproperty 'MS_Description', '3样品质量被接纳', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone3
GO

EXEC sp_addextendedproperty 'MS_Description', '4投标', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone4
GO

EXEC sp_addextendedproperty 'MS_Description', '5中标', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone5
GO

EXEC sp_addextendedproperty 'MS_Description', '6下订单', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone6
GO

EXEC sp_addextendedproperty 'MS_Description', '7交货', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone7
GO

EXEC sp_addextendedproperty 'MS_Description', '8销售确认', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone8
GO

EXEC sp_addextendedproperty 'MS_Description', '9项目失败', 'Schema', dbo, 'table', Prj_Milestone, 'column', Stone9
GO






--明细表        Bery        2014-05-23 11:51
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Prj_MilestoneDetail') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Prj_MilestoneDetail
GO


CREATE TABLE Prj_MilestoneDetail ( 
	Id nvarchar(200) NOT NULL,    --  主键Id 
	PrjCode nvarchar(200) NOT NULL,    --  项目编号 
	PrjName nvarchar(200) NOT NULL,    --  项目名称 
	UserCode nvarchar(200) NOT NULL,    --  用户编号 
	UserName nvarchar(200),    --  用户名称 
	DepCode int NOT NULL,    --  部门代码 
	DepName nvarchar(200),    --  部门名称 
	RptDate datetime NOT NULL,    --  上报日期 
	StoreAmount decimal(18,3) DEFAULT 0.0 NOT NULL,    --  项目储备额 
	ForeCast decimal(18,3) DEFAULT 0.0 NOT NULL,    --  今年预测 
	StoreSwitchRate decimal(18,3) DEFAULT 0.0 NOT NULL,    --  储备转换率 
	NextForeCast decimal(18,3) DEFAULT 0.0 NOT NULL,    --  明年预测 
	Stone1 int DEFAULT 0 NOT NULL,    --  初步洽谈 
	Stone2 int DEFAULT 0 NOT NULL,    --  提供样品 
	Stone3 int DEFAULT 0 NOT NULL,    --  样品质量被接纳 
	Stone4 int DEFAULT 0 NOT NULL,    --  投标 
	Stone5 int DEFAULT 0 NOT NULL,    --  中标 
	Stone6 int DEFAULT 0 NOT NULL,    --  下订单 
	Stone7 int DEFAULT 0 NOT NULL,    --  交货 
	Stone8 int DEFAULT 0 NOT NULL,    --  销售确认 
	Stone9 int DEFAULT 0 NOT NULL    --  项目失败 
)
GO

ALTER TABLE Prj_MilestoneDetail ADD CONSTRAINT PK_Prj_MilestoneDetail 
	PRIMARY KEY CLUSTERED (Id)
GO

EXEC sp_addextendedproperty 'MS_Description', '主键Id', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '项目编号', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', PrjCode
;

EXEC sp_addextendedproperty 'MS_Description', '项目名称', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', PrjName
;

EXEC sp_addextendedproperty 'MS_Description', '用户编号', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', UserCode
;

EXEC sp_addextendedproperty 'MS_Description', '用户名称', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', UserName
;

EXEC sp_addextendedproperty 'MS_Description', '部门代码', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', DepCode
;

EXEC sp_addextendedproperty 'MS_Description', '部门名称', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', DepName
;

EXEC sp_addextendedproperty 'MS_Description', '上报日期', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', RptDate
;

EXEC sp_addextendedproperty 'MS_Description', '项目储备额', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', StoreAmount
;

EXEC sp_addextendedproperty 'MS_Description', '今年预测', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', ForeCast
;

EXEC sp_addextendedproperty 'MS_Description', '储备转换率', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', StoreSwitchRate
;

EXEC sp_addextendedproperty 'MS_Description', '明年预测', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', NextForeCast
;

EXEC sp_addextendedproperty 'MS_Description', '初步洽谈', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone1
;

EXEC sp_addextendedproperty 'MS_Description', '提供样品', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone2
;

EXEC sp_addextendedproperty 'MS_Description', '样品质量被接纳', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone3
;

EXEC sp_addextendedproperty 'MS_Description', '投标', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone4
;

EXEC sp_addextendedproperty 'MS_Description', '中标', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone5
;

EXEC sp_addextendedproperty 'MS_Description', '下订单', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone6
;

EXEC sp_addextendedproperty 'MS_Description', '交货', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone7
;

EXEC sp_addextendedproperty 'MS_Description', '销售确认', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone8
;

EXEC sp_addextendedproperty 'MS_Description', '项目失败', 'Schema', dbo, 'table', Prj_MilestoneDetail, 'column', Stone9
;
GO
