CREATE TABLE `plus_project` (
  `UID_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL,
  `NAME_` VARCHAR(150) COLLATE gbk_chinese_ci DEFAULT NULL,
  `STARTDATE_` DATETIME DEFAULT NULL,
  `FINISHDATE_` DATETIME DEFAULT NULL,
  `LASTSAVED_` VARCHAR(20) COLLATE gbk_chinese_ci DEFAULT NULL,
  `CALENDARUID_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL,
  `CALENDARS_` TEXT COLLATE utf8_general_ci

);
CREATE TABLE `plus_resource` (
  `UID_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL,
  `NAME_` VARCHAR(200) COLLATE gbk_chinese_ci DEFAULT NULL,
  `TYPE_` INTEGER(11) DEFAULT NULL,
  `MAXUNITS_` INTEGER(11) DEFAULT NULL,
  `PROJECTUID_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL

);
CREATE TABLE `plus_task` (
  `UID_` VARCHAR(50) COLLATE gbk_chinese_ci NOT NULL DEFAULT '',
  `ID_` INTEGER(11) DEFAULT NULL,
  `NAME_` VARCHAR(200) COLLATE gbk_chinese_ci DEFAULT NULL,
  `START_` DATETIME DEFAULT NULL,
  `FINISH_` DATETIME DEFAULT NULL,
  `DURATION_` INTEGER(11) DEFAULT NULL,
  `WORK_` INTEGER(11) DEFAULT NULL,
  `PERCENTCOMPLETE_` INTEGER(11) DEFAULT NULL,
  `WEIGHT_` INTEGER(11) DEFAULT NULL,
  `CONSTRAINTTYPE_` INTEGER(11) DEFAULT NULL,
  `CONSTRAINTDATE_` DATETIME DEFAULT NULL,
  `MILESTONE_` INTEGER(11) DEFAULT NULL,
  `SUMMARY_` INTEGER(11) DEFAULT NULL,
  `CRITICAL_` INTEGER(11) DEFAULT NULL,
  `PRIORITY_` INTEGER(11) DEFAULT NULL,
  `NOTES_` VARCHAR(2000) COLLATE gbk_chinese_ci DEFAULT NULL,
  `DEPARTMENT_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL,
  `PRINCIPAL_` VARCHAR(500) COLLATE gbk_chinese_ci DEFAULT NULL,
  `PREDECESSORLINK_` VARCHAR(2000) COLLATE gbk_chinese_ci DEFAULT NULL,
  `FIXEDDATE_` INTEGER(11) DEFAULT NULL,
  `PARENTTASKUID_` VARCHAR(50) COLLATE gbk_chinese_ci NOT NULL DEFAULT '',
  `PROJECTUID_` VARCHAR(50) COLLATE gbk_chinese_ci DEFAULT NULL,  
  `ACTUALSTART_` DATETIME DEFAULT NULL,
  `ACTUALFINISH_` DATETIME DEFAULT NULL,
  `ACTUALDURATION_` INTEGER(11) DEFAULT NULL,
  `ASSIGNMENTS_` VARCHAR(2000) COLLATE gbk_chinese_ci DEFAULT NULL,
  `WBS_` VARCHAR(200) COLLATE gbk_chinese_ci DEFAULT NULL,
  `CRITICAL2_` INTEGER(11) DEFAULT NULL
	

);
