

using cn.justwin.DAL;
using System;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_OrgDi__OrgId__31B8F9AA", "PT_d_bm", RelationshipMultiplicity.ZeroOrOne, typeof(PT_d_bm), "Bud_OrgDiaryCost", RelationshipMultiplicity.Many, typeof(Bud_OrgDiaryCost), true)]
[assembly: EdmRelationship("Pm2Model", "FK__PT_PrjInf__PrjGu__0313E4B1", "PT_PrjInfo_ZTB_Detail", RelationshipMultiplicity.One, typeof(PT_PrjInfo_ZTB_Detail), "PT_PrjInfo_Kind", RelationshipMultiplicity.Many, typeof(PT_PrjInfo_Kind), true)]
[assembly: EdmRelationship("Pm2Model", "FK_plus_report", "plus_report", RelationshipMultiplicity.ZeroOrOne, typeof(plus_report), "plus_reportDetail", RelationshipMultiplicity.Many, typeof(plus_reportDetail), true)]
[assembly: EdmRelationship("Pm2Model", "用户_部门", "PT_d_bm", RelationshipMultiplicity.ZeroOrOne, typeof(PT_d_bm), "PT_yhmc", RelationshipMultiplicity.Many, typeof(PT_yhmc), true)]
[assembly: EdmRelationship("Pm2Model", "FK__PT_PrjInf__PrjGu__06E47595", "PT_PrjInfo_ZTB_Detail", RelationshipMultiplicity.One, typeof(PT_PrjInfo_ZTB_Detail), "PT_PrjInfo_Rank", RelationshipMultiplicity.Many, typeof(PT_PrjInfo_Rank), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_ConsT__ConsR__61DC42C1", "Bud_ConsReport", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_ConsReport), "Bud_ConsTask", RelationshipMultiplicity.Many, typeof(Bud_ConsTask), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_ConsT__ConsT__65ACD3A5", "Bud_ConsTask", RelationshipMultiplicity.One, typeof(Bud_ConsTask), "Bud_ConsTaskRes", RelationshipMultiplicity.Many, typeof(Bud_ConsTaskRes), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_ConsT__Resou__66A0F7DE", "Res_Resource", RelationshipMultiplicity.One, typeof(Res_Resource), "Bud_ConsTaskRes", RelationshipMultiplicity.Many, typeof(Bud_ConsTaskRes), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Attri__Resou__1A4AB916", "Res_ResourceType", RelationshipMultiplicity.ZeroOrOne, typeof(Res_ResourceType), "Res_Attribute", RelationshipMultiplicity.Many, typeof(Res_Attribute))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Price__Price__176E4C6B", "Res_PriceType", RelationshipMultiplicity.One, typeof(Res_PriceType), "Res_Price", RelationshipMultiplicity.Many, typeof(Res_Price), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Price__Resou__167A2832", "Res_Resource", RelationshipMultiplicity.One, typeof(Res_Resource), "Res_Price", RelationshipMultiplicity.Many, typeof(Res_Price), true)]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resou__Resou__10C14EDC", "Res_ResourceType", RelationshipMultiplicity.ZeroOrOne, typeof(Res_ResourceType), "Res_Resource", RelationshipMultiplicity.Many, typeof(Res_Resource))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resour__Unit__11B57315", "Res_Unit", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Unit), "Res_Resource", RelationshipMultiplicity.Many, typeof(Res_Resource))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resou__Paren__0DE4E231", "Res_ResourceType", RelationshipMultiplicity.ZeroOrOne, typeof(Res_ResourceType), "Res_ResourceType1", RelationshipMultiplicity.Many, typeof(Res_ResourceType))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resou__Attri__7D446614", "Res_Attribute", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Attribute), "Res_Resource", RelationshipMultiplicity.Many, typeof(Res_Resource))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Templ__Templ__61674175", "Res_Template", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Template), "Res_TemplateItem", RelationshipMultiplicity.Many, typeof(Res_TemplateItem))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Templ__Templ__2611717D", "Bud_TemplateType", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_TemplateType), "Bud_Template", RelationshipMultiplicity.Many, typeof(Bud_Template))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_TaskR__TaskI__269B8162", "Bud_Task", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_Task), "Bud_TaskResource", RelationshipMultiplicity.Many, typeof(Bud_TaskResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_TaskR__Resou__278FA59B", "Res_Resource", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Resource), "Bud_TaskResource", RelationshipMultiplicity.Many, typeof(Bud_TaskResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Templ__Templ__247E2EC6", "Bud_Template", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_Template), "Bud_TemplateItem", RelationshipMultiplicity.Many, typeof(Bud_TemplateItem))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Templ__Resou__338B682C", "Res_Resource", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Resource), "Bud_TemplateResource", RelationshipMultiplicity.Many, typeof(Bud_TemplateResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Templ__Templ__6DB809C1", "Bud_TemplateItem", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_TemplateItem), "Bud_TemplateResource", RelationshipMultiplicity.Many, typeof(Bud_TemplateResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Contr__Resou__705F6C42", "Res_Resource", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Resource), "Bud_ContractResource", RelationshipMultiplicity.Many, typeof(Bud_ContractResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Contr__TaskI__6F6B4809", "Bud_ContractTask", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_ContractTask), "Bud_ContractResource", RelationshipMultiplicity.Many, typeof(Bud_ContractResource))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resou__TaskI__63F9955D", "Bud_Task", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_Task), "Res_ResourceTemp", RelationshipMultiplicity.Many, typeof(Res_ResourceTemp))]
[assembly: EdmRelationship("Pm2Model", "FK__Res_Resou__Resou__63057124", "Res_Resource", RelationshipMultiplicity.ZeroOrOne, typeof(Res_Resource), "Res_ResourceTemp", RelationshipMultiplicity.Many, typeof(Res_ResourceTemp))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Indir__Indir__0801EBA9", "Bud_IndirectBudget", RelationshipMultiplicity.One, typeof(Bud_IndirectBudget), "Bud_IndirectMonthBudget", RelationshipMultiplicity.Many, typeof(Bud_IndirectMonthBudget))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Indir__InDia__0D85BAD5", "Bud_IndirectDiaryCost", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_IndirectDiaryCost), "Bud_IndirectDiaryDetails", RelationshipMultiplicity.Many, typeof(Bud_IndirectDiaryDetails))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_Organ__Organ__69D26A44", "Bud_OrganizationBudget", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_OrganizationBudget), "Bud_OrganizationMonthBudget", RelationshipMultiplicity.Many, typeof(Bud_OrganizationMonthBudget))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_OrgDi__OrgDi__48C67C34", "Bud_OrgDiaryCost", RelationshipMultiplicity.ZeroOrOne, typeof(Bud_OrgDiaryCost), "Bud_OrgDiaryDetails", RelationshipMultiplicity.Many, typeof(Bud_OrgDiaryDetails))]
[assembly: EdmRelationship("Pm2Model", "FK__Basic_Cod__TypeC__37A6DD2A", "Basic_CodeType", RelationshipMultiplicity.One, typeof(Basic_CodeType), "Basic_CodeList", RelationshipMultiplicity.Many, typeof(Basic_CodeList), true)]
[assembly: EdmRelationship("Pm2Model", "FK__PT_PrjMem__Membe__40071901", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "PT_PrjMember", RelationshipMultiplicity.Many, typeof(PT_PrjMember))]
[assembly: EdmRelationship("Pm2Model", "FK__PT_Prj_Co__Input__5EE0A5DC", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "PT_Prj_Completed", RelationshipMultiplicity.Many, typeof(PT_Prj_Completed))]
[assembly: EdmRelationship("Pm2Model", "FK__PT_Prj_Co__PrjCo__6A525888", "PT_Prj_Completed", RelationshipMultiplicity.ZeroOrOne, typeof(PT_Prj_Completed), "PT_Prj_Completed_Detail", RelationshipMultiplicity.Many, typeof(PT_Prj_Completed_Detail))]
[assembly: EdmRelationship("Pm2Model", "FK__PT_Prj_Co__Input__6B467CC1", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "PT_Prj_Completed_Detail", RelationshipMultiplicity.Many, typeof(PT_Prj_Completed_Detail))]
[assembly: EdmRelationship("Pm2Model", "FK__PT_Prj_Co__Detai__32CD1974", "PT_Prj_Completed_Detail", RelationshipMultiplicity.ZeroOrOne, typeof(PT_Prj_Completed_Detail), "PT_Prj_Completed_Annex", RelationshipMultiplicity.Many, typeof(PT_Prj_Completed_Annex))]
[assembly: EdmRelationship("Pm2Model", "FK_plus_progress_InputUser", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "plus_progress", RelationshipMultiplicity.Many, typeof(plus_progress))]
[assembly: EdmRelationship("Pm2Model", "FK_privilege_ProgressId", "plus_progress", RelationshipMultiplicity.One, typeof(plus_progress), "plus_progress_privilege", RelationshipMultiplicity.Many, typeof(plus_progress_privilege))]
[assembly: EdmRelationship("Pm2Model", "FK_progress_version_ProgressId", "plus_progress", RelationshipMultiplicity.One, typeof(plus_progress), "plus_progress_version", RelationshipMultiplicity.Many, typeof(plus_progress_version))]
[assembly: EdmRelationship("Pm2Model", "FK_privilege_UserCode", "PT_yhmc", RelationshipMultiplicity.One, typeof(PT_yhmc), "plus_progress_privilege", RelationshipMultiplicity.Many, typeof(plus_progress_privilege))]
[assembly: EdmRelationship("Pm2Model", "FK_progress_version_InputUser", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "plus_progress_version", RelationshipMultiplicity.Many, typeof(plus_progress_version))]
[assembly: EdmRelationship("Pm2Model", "FK__Bud_TaskC__Input__292EA0A1", "PT_yhmc", RelationshipMultiplicity.ZeroOrOne, typeof(PT_yhmc), "Bud_TaskChange", RelationshipMultiplicity.Many, typeof(Bud_TaskChange), true)]
[assembly: EdmRelationship("Pm2Model", "FK_plus_progress_version", "plus_progress_version", RelationshipMultiplicity.ZeroOrOne, typeof(plus_progress_version), "plus_report", RelationshipMultiplicity.Many, typeof(plus_report), true)]
[assembly: EdmSchema]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("FANPUSOFT")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCopyright("版权所有 (C) FANPUSOFT 2015")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyProduct("PmDataAccess")]
[assembly: AssemblyTitle("PmDataAccess")]
[assembly: AssemblyTrademark("")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: ComVisible(false)]
[assembly: Guid("77e33095-687d-497b-a7a9-ea3ba3c553f1")]
